<?php

function penjualan_menu() {
	$items['penjualan/kasir'] = array(
    'title' => t('Kasir Global POS'),
    'description' => 'Kasir Global POS',
		'page callback' => 'penjualan',
		'access callback' => 'user_access',
		'access arguments' => array('Admin Penjualan Produk'),
		'type' => MENU_CALLBACK,
		'file' => 'globalpos.kasir.inc'
	);
	$items['penjualan/laundry'] = array(
    'title' => t('Laundry Masuk'),
    'description' => 'Form laundry masuk',
		'page callback' => 'laundry',
		'access callback' => 'user_access',
		'access arguments' => array('Input Laundry'),
		'type' => MENU_CALLBACK,
		'file' => 'globalpos.laundry.inc'
	);
	$items['penjualan/customerorder'] = array(
		'title' => t('Customer Order'),
		'description' => 'Form customer order',
		'page callback' => 'customerorder',
		'access callback' => 'user_access',
		'access arguments' => array('Input Customer Order'),
		'type' => MENU_CALLBACK,
		'file' => 'globalpos.customerorder.inc'
	);
	$items['penjualan/viewpenjualan'] = array(
    'title' => t('Data Penjualan'),
    'description' => 'Data Penjualan',
		'page callback' => 'view_tabel_penjualan',
		'access callback' => 'user_access',
		'access arguments' => array('Admin Data Penjualan Produk'),
		'type' => MENU_CALLBACK,
		'file' => 'globalpos.penjualan.inc'
	);
	$items['penjualan/viewlaundry'] = array(
    'title' => t('Data Laundry'),
    'description' => 'Data Laundry',
		'page callback' => 'view_tabel_laundry',
		'access callback' => 'user_access',
		'access arguments' => array('Admin Data Penjualan Produk'),
		'type' => MENU_CALLBACK,
		'file' => 'globalpos.tabellaundry.inc'
	);
	$items['penjualan/detailpenjualan'] = array(
    'title' => t('Detail Penjualan'),
    'description' => 'Detail Penjualan',
		'page callback' => 'detail_penjualan',
		'access callback' => 'user_access',
		'access arguments' => array('Admin Data Penjualan Produk'),
		'type' => MENU_CALLBACK,
		'file' => 'globalpos.penjualan.inc'
	);
	$items['penjualan/detaillaundry'] = array(
    'title' => t('Detail Laundry'),
    'description' => 'Detail Laundry',
		'page callback' => 'detail_laundry',
		'access callback' => 'user_access',
		'access arguments' => array('Admin Data Penjualan Produk'),
		'type' => MENU_CALLBACK,
		'file' => 'globalpos.tabellaundry.inc'
	);
	$items['penjualan/cariproduk'] = array(
    'title' => t('Pencarian Produk'),
    'description' => 'Pencarian Produk',
		'page callback' => 'cari_produk',
		'access callback' => 'user_access',
		'access arguments' => array('Admin Penjualan Produk'),
		'type' => MENU_CALLBACK,
		'file' => 'globalpos.kasir.inc'
	);
	$items['penjualan/autocaribarang'] = array(
    'title' => t('Pencarian Produk'),
    'description' => 'Pencarian Produk',
		'page callback' => 'cari_barang',
		'access callback' => 'user_access',
		'access arguments' => array('Admin Penjualan Produk'),
		'type' => MENU_CALLBACK,
		'file' => 'globalpos.kasir.inc'
	);
	$items['penjualan/simpanpenjualan'] = array(
    'title' => t('Simpan Penjualan'),
    'description' => 'Simpan Penjualan',
		'page callback' => 'simpan_penjualan',
		'access callback' => 'user_access',
		'access arguments' => array('Admin Penjualan Produk'),
		'type' => MENU_CALLBACK,
		'file' => 'globalpos.kasir.inc'
	);
	$items['penjualan/simpanlaundry'] = array(
    'title' => t('Simpan Laundry Masuk'),
    'description' => 'Simpan laundry masuk',
		'page callback' => 'simpan_laundry',
		'access callback' => 'user_access',
		'access arguments' => array('Input Laundry'),
		'type' => MENU_CALLBACK,
		'file' => 'globalpos.laundry.inc'
	);
	$items['penjualan/simpancustomerorder'] = array(
		'title' => t('Simpan Customer Order'),
		'description' => 'Simpan customer order',
		'page callback' => 'simpan_customerorder',
		'access callback' => 'user_access',
		'access arguments' => array('Input Customer Order'),
		'type' => MENU_CALLBACK,
		'file' => 'globalpos.customerorder.inc'
	);
	$items['penjualan/hitungomset'] = array(
    'title' => t('Hitung Omset'),
    'description' => 'Hitung Omset',
		'page callback' => 'hitung_omset',
		'access callback' => 'user_access',
		'access arguments' => array('Admin Penjualan Produk'),
		'type' => MENU_CALLBACK,
		'file' => 'globalpos.kasir.inc'
	);
	$items['penjualan/updatepenjualan'] = array(
    'title' => t('Update Penjualan'),
    'description' => t('Update Penjualan'),
		'page callback' => 'update_penjualan',
		'access callback' => 'user_access',
		'access arguments' => array('Admin Penjualan Produk'),
		'type' => MENU_CALLBACK,
		'file' => 'penjualan.update.inc'
	);
	$items['penjualan/updatelaundry'] = array(
    'title' => t('Update Laundry'),
    'description' => t('Update Laundry'),
		'page callback' => 'update_laundry',
		'access callback' => 'user_access',
		'access arguments' => array('Admin Penjualan Produk'),
		'type' => MENU_CALLBACK,
		'file' => 'penjualan.update.inc'
	);
	$items['penjualan/deletepenjualan'] = array(
    'title' => t('Delete Penjualan'),
    'description' => t('Delete Penjualan'),
		'page callback' => 'delete_penjualan',
		'access callback' => 'user_access',
		'access arguments' => array('Admin Penjualan Produk'),
		'type' => MENU_CALLBACK,
		'file' => 'penjualan.delete.inc'
	);
	$items['penjualan/deletelaundry'] = array(
    'title' => t('Delete Laundry'),
    'description' => t('Delete Laundry'),
		'page callback' => 'delete_laundry',
		'access callback' => 'user_access',
		'access arguments' => array('Admin Penjualan Produk'),
		'type' => MENU_CALLBACK,
		'file' => 'penjualan.delete.inc'
	);
	$items['penjualan/getrandomstring'] = array(
		'title' => t('Get Random String'),
		'description' => t('Get Random String'),
		'page callback' => 'getRandomStringAjax',
		'access callback' => 'user_access',
		'access arguments' => array('Admin Penjualan Produk'),
		'type' => MENU_CALLBACK,
	);
	$items['penjualan/viewcustomerorder'] = array(
		'title' => t('Data Customer Order'),
		'description' => 'Data customer order',
		'page callback' => 'view_tabel_customerorder',
		'access callback' => 'user_access',
		'access arguments' => array('Admin Data Customer Order'),
		'type' => MENU_CALLBACK,
		'file' => 'globalpos.tabelcustomerorder.inc'
	);
	$items['penjualan/deletecustomerorder/%'] = array(
		'title' => t('Delete Customer Order'),
		'description' => t('Delete Customer Order'),
		'page callback' => 'delete_customer_order',
		'page arguments' => array(2),
		'access callback' => 'user_access',
		'access arguments' => array('Admin Data Customer Order'),
		'type' => MENU_CALLBACK,
		'file' => 'penjualan.delete.inc'
	);
	$items['penjualan/detailcustomerorder'] = array(
		'title' => t('Detail Customer Order'),
		'description' => 'Detail customer order',
		'page callback' => 'detail_customerorder',
		'access callback' => 'user_access',
		'access arguments' => array('Admin Data Customer Order'),
		'type' => MENU_CALLBACK,
		'file' => 'globalpos.tabelcustomerorder.inc'
	);
	$items['penjualan/laundrykeluar'] = array(
		'title' => t('Pengambilan Laundry'),
		'description' => 'Form laundry keluar',
		'page callback' => 'laundry_keluar',
		'access callback' => 'user_access',
		'access arguments' => array('Input Laundry'),
		'type' => MENU_CALLBACK,
		'file' => 'globalpos.laundry.inc'
	);
	$items['penjualan/carinotalaundry'] = array(
		'title' => t('Pencarian Nota Laundry'),
		'description' => 'Pencarian Nota Laundry',
		'page callback' => 'cari_nota_laundry',
		'access callback' => 'user_access',
		'access arguments' => array('Input Laundry'),
		'type' => MENU_CALLBACK,
		'file' => 'globalpos.laundry.inc'
	);
	$items['penjualan/updateraklaundry'] = array(
		'title' => t('Update Nomer Rak Laundry'),
		'description' => 'Update nomer rak laundry',
		'page callback' => 'update_no_rak_laundry',
		'access callback' => 'user_access',
		'access arguments' => array('Input Laundry'),
		'type' => MENU_CALLBACK,
		'file' => 'globalpos.tabellaundry.inc'
	);
	$items['penjualan/orderkeluar'] = array(
		'title' => t('Pengambilan Order/Pesanan'),
		'description' => 'Form pengambilan order/pesanan',
		'page callback' => 'order_keluar',
		'access callback' => 'user_access',
		'access arguments' => array('Input Customer Order'),
		'type' => MENU_CALLBACK,
		'file' => 'globalpos.customerorder.inc'
	);
	$items['penjualan/carinotaorder'] = array(
		'title' => t('Pencarian Nota Order'),
		'description' => 'Pencarian Nota Order',
		'page callback' => 'cari_nota_order',
		'access callback' => 'user_access',
		'access arguments' => array('Input Customer Order'),
		'type' => MENU_CALLBACK,
		'file' => 'globalpos.customerorder.inc'
	);
	$items['penjualan/orderselesai'] = array(
		'title' => t('Input Hasil Produksi'),
		'description' => 'Form input hasil produksi',
		'page callback' => 'order_selesai',
		'access callback' => 'user_access',
		'access arguments' => array('Input Customer Order'),
		'type' => MENU_CALLBACK,
		'file' => 'globalpos.customerorder.inc'
	);
	$items['penjualan/carinotaproduksi'] = array(
		'title' => t('Pencarian Nota Produksi'),
		'description' => 'Pencarian Nota Produksi',
		'page callback' => 'cari_nota_produksi',
		'access callback' => 'user_access',
		'access arguments' => array('Input Customer Order'),
		'type' => MENU_CALLBACK,
		'file' => 'globalpos.customerorder.inc'
	);
	$items['penjualan/simpanhasilproduksi'] = array(
		'title' => t('Simpan Hasil Produksi'),
		'description' => 'Simpan hasil produksi',
		'page callback' => 'simpan_hasil_produksi',
		'access callback' => 'user_access',
		'access arguments' => array('Input Customer Order'),
		'type' => MENU_CALLBACK,
		'file' => 'globalpos.customerorder.inc'
	);
	$items['penjualan/updatedetailpenjualan'] = array(
		'title' => t('Update Detail Penjualan'),
		'description' => 'Update detail penjualan',
		'page callback' => 'update_detail_penjualan',
		'access callback' => 'user_access',
		'access arguments' => array('Admin Data Penjualan Produk'),
		'type' => MENU_CALLBACK,
		'file' => 'penjualan.update.inc'
	);
	$items['penjualan/deletedetailpenjualan'] = array(
		'title' => t('Delete Detail Penjualan'),
		'description' => 'Delete detail penjualan',
		'page callback' => 'delete_detail_penjualan_ajax',
		'access callback' => 'user_access',
		'access arguments' => array('Admin Data Penjualan Produk'),
		'type' => MENU_CALLBACK,
		'file' => 'penjualan.delete.inc'
	);
	$items['penjualan/simpandetailpenjualan'] = array(
		'title' => t('Insert Detail Penjualan'),
		'description' => 'Insert detail penjualan',
		'page callback' => 'insert_detail_penjualan',
		'access callback' => 'user_access',
		'access arguments' => array('Admin Data Penjualan Produk'),
		'type' => MENU_CALLBACK,
		'file' => 'penjualan.update.inc'
	);
	$items['penjualan/exportfaktur/%'] = array(
		'title' => t('Export faktur ke xls'),
		'description' => 'Export faktur ke xls',
		'page callback' => 'create_faktur_in_excel',
		'page arguments' => array(2),
		'access callback' => 'user_access',
		'access arguments' => array('Admin Data Penjualan Produk'),
		'type' => MENU_CALLBACK,
	);
	return $items;
} // end hook menu

function penjualan_perm() {
	return array('Admin Penjualan Produk','Admin Data Penjualan Produk','Input Laundry','Input Customer Order','Admin Data Customer Order','Access Data Customer Order');
}

require_once 'attachplugins.inc';
require_once 'penjualan.api.inc';

function getRandomStringAjax(){
	print create_barcode_batch();
	exit();
}
function get_updated_penjualan(){
	$strSQL = 'SELECT idpenjualan, nonota, idtitipanlaundry, idcustomerorder, tglpenjualan, idpemakai, ';
	$strSQL .= 'idpelanggan, total, totalmodal, carabayar, bayar, kembali, perlakuankembalian, ';
	$strSQL .= 'nokartu, keterangan, insert_date ';
	$strSQL .= 'FROM penjualan WHERE uploaded=0';
	$result = db_query($strSQL);
	$dataPenjualan = array();
	while ($data = db_fetch_array($result)){
		$dataPenjualan[] = $data;
	}
	return $dataPenjualan;
}
function create_faktur_in_excel($idpenjualan = 0){
	$namafile = '';
	if (!empty($idpenjualan)){
		if (function_exists('arrayBulan')){
			$bulan = arrayBulan();
		}else{
			$bulan = array(
				1 => 'Januari',
				2 => 'Februari',
				3 => 'Maret',
				4 => 'April',
				5 => 'Mei',
				6 => 'Juni',
				7 => 'Juli',
				8 => 'Agustus',
				9 => 'September',
				10 => 'Oktober',
				11 => 'November',
				12 => 'Desember',
			);
		}
		$dataPremis = getPremisInformation();
		$dataPenjualan = getDataPenjualan($idpenjualan);
		if (!file_check_location('sites/all/libraries/PHPExcel/PHPExcel.php', 'sites/all/libraries/PHPExcel')) {
			watchdog('phpexcel', "Couldn't find the PHPExcel library! ", array(), WATCHDOG_ERROR);
			return FALSE;
		}
		require_once 'sites/all/libraries/PHPExcel/PHPExcel.php';
		$objReader = PHPExcel_IOFactory::createReader('Excel2007');
		$objPHPExcel = $objReader->load("sites/default/files/templates/template-faktur.xlsx");
		/*
		 * A2: Alamat Premis A3: Telepon Premis
		 * B5 : Nomer Nota, B6: Nama Pelanggan, B7 : Alamat Pelanggan, I5: Tanggal (format 01 Januari 2017), I6: Cara pembayaran
		*/

		/* Set Style */
		$BStyle = array(
			'borders' => array(
				'outline' => array(
					'style' => PHPExcel_Style_Border::BORDER_THIN
				)
			)
		);
		$alignmentStyle = array(
			'alignment' => array(
				'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
				'vertical' => PHPExcel_Style_Alignment::VERTICAL_CENTER,
			)
		);
		$alignmentStyle2 = array(
			'alignment' => array(
				'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
				'vertical' => PHPExcel_Style_Alignment::VERTICAL_TOP,
			)
		);
		$alignmentLeft = array(
			'alignment' => array(
				'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT
			)
		);
		$styleBg1 = array(
			'fill' => array(
				'type' => PHPExcel_Style_Fill::FILL_SOLID,
				'color' => array('rgb' => 'FFC7CE')
			)
		);
		$styleBg2 = array(
			'fill' => array(
				'type' => PHPExcel_Style_Fill::FILL_SOLID,
				'color' => array('rgb' => 'C6EFCE')
			)
		);
		$styleBg3 = array(
			'fill' => array(
				'type' => PHPExcel_Style_Fill::FILL_SOLID,
				'color' => array('rgb' => 'FFEB9C')
			)
		);

		/* Select Sheet 1 */
		$objPHPExcel->setActiveSheetIndex(0);
		$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
		$objPHPExcel->getActiveSheet()->setCellValue('A1', strtoupper($dataPremis->nama));
		$objPHPExcel->getActiveSheet()->setCellValue('A2','Alamat :');
		$objPHPExcel->getActiveSheet()->mergeCells('B2:D2');
		$objPHPExcel->getActiveSheet()->setCellValue('B2',$dataPremis->alamat);
		$objPHPExcel->getActiveSheet()->getStyle('A1:D2')->applyFromArray($alignmentStyle2);
		$objPHPExcel->getActiveSheet()->getStyle('B2:D2')->getAlignment()->setWrapText(true);
		$objPHPExcel->getActiveSheet()->getRowDimension(2)->setRowHeight(45);
		$objPHPExcel->getActiveSheet()->setCellValue('A3','Telepon : '.$dataPremis->telepon);
		$objPHPExcel->getActiveSheet()->setCellValue('B5',':  '.$dataPenjualan['info']->nonota);
		$objPHPExcel->getActiveSheet()->setCellValue('B6',':  '.strtoupper($dataPenjualan['info']->namapelanggan));
		$objPHPExcel->getActiveSheet()->setCellValue('B7',':  '.strtoupper($dataPenjualan['info']->alamat));
		$explodeTgl = explode(' ',$dataPenjualan['info']->tglpenjualan);
		$explodeTglJual = explode('-',$explodeTgl[0]);
		$tglJual = $explodeTglJual[2].' '.$bulan[(int)$explodeTglJual[1]].' '.$explodeTglJual[0];
		$objPHPExcel->getActiveSheet()->setCellValue('J5',':  '.$tglJual);
		$objPHPExcel->getActiveSheet()->setCellValue('J6',':  '.$dataPenjualan['info']->carabayar);
		$alphas = range('A', 'Z');
		$rownumber = 10;
		/*
 		* A10: Nomer, B10: Nama Barang, C10: Barcode, D10: Qty, E10: Satuan, F10: Harga, G10: Diskon,  H10: Subtotal
		*/
		$jumlahTotal = 0;
		$totalQty1 = 0;
		$totalQty2 = 0;
		for ($i = 0; $i < count($dataPenjualan['detail']);$i++){
			$detailPenjualan = $dataPenjualan['detail'][$i];
			$colnumber = 0;
			$objPHPExcel->getActiveSheet()->setCellValue($alphas[$colnumber].$rownumber, ($i + 1));
			$colnumber++;
			$objPHPExcel->getActiveSheet()->setCellValue($alphas[$colnumber].$rownumber, trim(strtoupper($detailPenjualan->namaproduct)));
			$colnumber++;
			$ukuran = !empty($detailPenjualan->ukuran) ? $detailPenjualan->ukuran : '-';
			$objPHPExcel->getActiveSheet()->setCellValue($alphas[$colnumber].$rownumber, $ukuran);
			$colnumber++;
			$barcode = !empty($detailPenjualan->barcode) ? $detailPenjualan->barcode : '-';
			$objPHPExcel->getActiveSheet()->setCellValue($alphas[$colnumber].$rownumber, trim($barcode));
			$colnumber++;
			$objPHPExcel->getActiveSheet()->setCellValue($alphas[$colnumber].$rownumber, $detailPenjualan->jumlah);
			$totalQty1 = $totalQty1 + $detailPenjualan->jumlah;
			$colnumber++;
			$objPHPExcel->getActiveSheet()->setCellValue($alphas[$colnumber].$rownumber, strtoupper($detailPenjualan->satuan));
			$colnumber++;
			$objPHPExcel->getActiveSheet()->setCellValue($alphas[$colnumber].$rownumber, $detailPenjualan->hargajual);
			$objPHPExcel->getActiveSheet()->getStyle($alphas[$colnumber].$rownumber)->getNumberFormat()->setFormatCode('_("Rp"* #,##0.00_);_("Rp"* \(#,##0.00\);_("Rp"* "-"??_);_(@_)');
			$colnumber++;
			$konversiSatuan = get_konversi_satuan(strtoupper($detailPenjualan->satuan));
			if (!empty($konversiSatuan)) {
				$objPHPExcel->getActiveSheet()->setCellValue($alphas[$colnumber] . $rownumber, $konversiSatuan * $detailPenjualan->jumlah);
				$totalQty2 = $totalQty2 + ($konversiSatuan * $detailPenjualan->jumlah);
				$colnumber++;
				$objPHPExcel->getActiveSheet()->setCellValue($alphas[$colnumber] . $rownumber, round($detailPenjualan->hargajual / $konversiSatuan));
				$objPHPExcel->getActiveSheet()->getStyle($alphas[$colnumber] . $rownumber)->getNumberFormat()->setFormatCode('_("Rp"* #,##0.00_);_("Rp"* \(#,##0.00\);_("Rp"* "-"??_);_(@_)');
				$colnumber++;
			}else{
				$objPHPExcel->getActiveSheet()->setCellValue($alphas[$colnumber] . $rownumber, '-');
				$colnumber++;
				$objPHPExcel->getActiveSheet()->setCellValue($alphas[$colnumber] . $rownumber, '-');
				$colnumber++;
			}
			$subTotal = ($detailPenjualan->hargajual - ($detailPenjualan->hargajual*$detailPenjualan->diskon/100))*$detailPenjualan->jumlah;
			$objPHPExcel->getActiveSheet()->setCellValue($alphas[$colnumber].$rownumber, $subTotal);
			$objPHPExcel->getActiveSheet()->getStyle($alphas[$colnumber].$rownumber)->getNumberFormat()->setFormatCode('_("Rp"* #,##0.00_);_("Rp"* \(#,##0.00\);_("Rp"* "-"??_);_(@_)');
			$rownumber++;
			$jumlahTotal = $jumlahTotal + $subTotal;
		}
		$styleArray = array(
			'borders' => array(
				'allborders' => array(
					'style' => PHPExcel_Style_Border::BORDER_THIN
				)
			)
		);
		$objPHPExcel->getActiveSheet()->getStyle('A10:J'.($rownumber - 1))->applyFromArray($styleArray);
		unset($styleArray);
		$objPHPExcel->getActiveSheet()->mergeCells('A'.$rownumber.':B'.($rownumber + 1));
		$objPHPExcel->getActiveSheet()->setCellValue('A'.$rownumber, strtoupper($dataPremis->nama));
		$objPHPExcel->getActiveSheet()->getStyle('A'.$rownumber.':B'.($rownumber + 1))->applyFromArray($alignmentStyle);
		$objPHPExcel->getActiveSheet()->getStyle('A'.$rownumber)->getFont()->setBold(true);
		$objPHPExcel->getActiveSheet()->mergeCells('A'.($rownumber + 4).':B'.($rownumber + 4));
		$objPHPExcel->getActiveSheet()->setCellValue('A'.($rownumber + 4), '.....................................');
		$objPHPExcel->getActiveSheet()->getStyle('A'.($rownumber + 4).':B'.($rownumber + 4))->applyFromArray($alignmentStyle);
		$objPHPExcel->getActiveSheet()->getStyle('A'.$rownumber.':B'.($rownumber + 4))->applyFromArray($BStyle);
		$objPHPExcel->getActiveSheet()->mergeCells('C'.$rownumber.':D'.($rownumber + 1));
		$objPHPExcel->getActiveSheet()->setCellValue('C'.$rownumber, 'PENERIMA');
		$objPHPExcel->getActiveSheet()->getStyle('C'.$rownumber)->getFont()->setBold(true);
		$objPHPExcel->getActiveSheet()->mergeCells('C'.($rownumber + 4).':D'.($rownumber + 4));
		$objPHPExcel->getActiveSheet()->setCellValue('C'.($rownumber + 4), '..............................');
		$objPHPExcel->getActiveSheet()->getStyle('C'.($rownumber + 4).':D'.($rownumber + 4))->applyFromArray($alignmentStyle);
		$objPHPExcel->getActiveSheet()->getStyle('C'.$rownumber.':H'.($rownumber + 4))->applyFromArray($BStyle);
		$objPHPExcel->getActiveSheet()->setCellValue('E'.$rownumber, $totalQty1);
		$objPHPExcel->getActiveSheet()->getStyle('E'.$rownumber)->applyFromArray($alignmentStyle);
		$objPHPExcel->getActiveSheet()->getStyle('E'.$rownumber)->getFont()->setBold(true);
		$objPHPExcel->getActiveSheet()->setCellValue('H'.$rownumber, $totalQty2);
		$objPHPExcel->getActiveSheet()->getStyle('H'.$rownumber)->getFont()->setBold(true);
		$objPHPExcel->getActiveSheet()->getStyle('H'.$rownumber)->applyFromArray($alignmentStyle);
		$objPHPExcel->getActiveSheet()->setCellValue('I'.$rownumber, 'TOTAL');
		$objPHPExcel->getActiveSheet()->setCellValue('J'.$rownumber, $jumlahTotal);
		$objPHPExcel->getActiveSheet()->getStyle('J'.$rownumber)->getNumberFormat()->setFormatCode('_("Rp"* #,##0.00_);_("Rp"* \(#,##0.00\);_("Rp"* "-"??_);_(@_)');
		$objPHPExcel->getActiveSheet()->getStyle('I'.$rownumber.':J'.$rownumber)->applyFromArray($styleBg1);
		$objPHPExcel->getActiveSheet()->setCellValue('I'.($rownumber + 1), 'ONGKIR');
		$objPHPExcel->getActiveSheet()->getStyle('I'.($rownumber + 1).':J'.($rownumber + 1))->applyFromArray($styleBg2);
		$objPHPExcel->getActiveSheet()->setCellValue('I'.($rownumber + 2), 'JUMLAH');
		$objPHPExcel->getActiveSheet()->mergeCells('I'.($rownumber + 3).':J'.($rownumber + 4));
		$objPHPExcel->getActiveSheet()->setCellValue('I'.($rownumber + 3), $jumlahTotal);
		$objPHPExcel->getActiveSheet()->getStyle('I'.($rownumber + 3))->getNumberFormat()->setFormatCode('_("Rp"* #,##0.00_);_("Rp"* \(#,##0.00\);_("Rp"* "-"??_);_(@_)');
		$objPHPExcel->getActiveSheet()->getStyle('I'.$rownumber.':I'.($rownumber + 2))->applyFromArray($alignmentLeft);
		$objPHPExcel->getActiveSheet()->getStyle('I'.$rownumber.':J'.($rownumber + 4))->applyFromArray($BStyle);
		$objPHPExcel->getActiveSheet()->getStyle('I'.($rownumber + 3))->getFont()->setSize(16);
		$objPHPExcel->getActiveSheet()->getStyle('I'.($rownumber + 3))->getFont()->setBold(true);
		$objPHPExcel->getActiveSheet()->getStyle('I'.($rownumber + 2).':J'.($rownumber + 3))->applyFromArray($styleBg3);
		$waktu = time();
		$namafile = 'penjualan-'.$dataPenjualan['info']->nonota.'-'.$waktu.'.xlsx';
		$objWriter->save('sites/default/files/'.$namafile);
	}
	print $namafile;
	exit();
}